from effort.model import EffortCLIP

def get_model(opt):
    return EffortCLIP(
        clip_model_or_path=getattr(opt, "clip_model", None),
        enable_osd_regs=bool(getattr(opt, "osd_regs", False)),
        freeze_backbone=bool(getattr(opt, "fix_backbone", False)),
        patch_pool=True,
        patch_pool_tau=float(getattr(opt, "patch_pool_tau", 1.5)),
        patch_pool_mode=str(getattr(opt, "patch_pool_mode", "lse")),
        patch_trim_p=float(getattr(opt, "patch_trim_p", 0.2)),
        patch_quality=str(getattr(opt, "patch_quality", "none")),
        svd_cache_enable=bool(getattr(opt, "svd_cache_enable", True)),
        svd_cache_dir=str(getattr(opt, "svd_cache_dir", "cache")),
        svd_init_device=str(getattr(opt, "svd_init_device", "auto")),
        svd_show_progress=bool(getattr(opt, "svd_show_progress", True)),
        svd_rank_cap=getattr(opt, "svd_rank_cap", None),
        multi_expert_enable=bool(getattr(opt, "multi_expert_enable", False)),
        multi_expert_k=int(getattr(opt, "multi_expert_k", 1)),
        multi_expert_route=str(getattr(opt, "multi_expert_route", "quality_bin")),
        multi_expert_route_temp=float(getattr(opt, "multi_expert_route_temp", 1.0)),
        multi_expert_route_detach=bool(getattr(opt, "multi_expert_route_detach", True)),
        multi_expert_hybrid_mix=float(getattr(opt, "multi_expert_hybrid_mix", 0.0)),
        route_sup_lambda=float(getattr(opt, "multi_expert_route_sup_lambda", 0.0)),
        route_bal_lambda=float(getattr(opt, "multi_expert_balance_lambda", 0.0)),
        expert_div_lambda=float(getattr(opt, "multi_expert_div_lambda", 0.0)),
        rank_loss_enable=bool(getattr(opt, "rank_loss_enable", False)),
        rank_loss_mode=str(getattr(opt, "rank_loss_mode", "logistic")),
        rank_loss_margin=float(getattr(opt, "rank_loss_margin", 0.2)),
        rank_loss_max_pairs=int(getattr(opt, "rank_loss_max_pairs", 1024)),
        quality_cuts=getattr(opt, "quality_cuts", None),
        degrade_router_dim=int(getattr(opt, "degrade_router_dim", 128)),
        degrade_router_dropout=float(getattr(opt, "degrade_router_dropout", 0.1)),
        restoration_enable=bool(getattr(opt, "restoration_enable", False)),
        restoration_strength=float(getattr(opt, "restoration_strength", 0.20)),
        adapter_last_n_layers=int(getattr(opt, "adapter_last_n_layers", 0)),
        svd_residual_mode=str(getattr(opt, "svd_residual_mode", "add")),
        svd_residual_gate_init=float(getattr(opt, "svd_residual_gate_init", 0.0)),
        svd_residual_train_mode=str(getattr(opt, "svd_residual_train_mode", "full")),
        peft_unfreeze_last_n_blocks=int(getattr(opt, "peft_unfreeze_last_n_blocks", 0)),
        peft_unfreeze_layernorm=bool(getattr(opt, "peft_unfreeze_layernorm", True)),
        peft_unfreeze_bias=bool(getattr(opt, "peft_unfreeze_bias", False)),
    )

__all__ = ["EffortCLIP", "get_model"]
